// TickerqSample/Generated/JobExecutionHelpers.Stub.cs
namespace TickerqSample.BackgroundJobs.Base;

public static partial class AutoGenerated
{
    // This empty partial class allows the project to compile
    // The source generator will add methods to it
}